safe:        false
auto:        false

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    true

markdown: rdiscount

encoding: utf-8

changefreq: daily


